### ISSUE TITLE
Malware detected in release?

### ISSUE THREAD

**Issue by oyvindln** [umezawatakeshi/utvideo#31]
Several anti-virus engines detect malware in the latest releases:

https://www.virustotal.com/gui/file/0f7aeb009e933536581d10b2cfa3909016f814b411f5a920434fd87ec0139ef5/detection

And people report it being removed by anti-virus:

https://forum.videohelp.com/threads/396238-Utvideo-adware-malware-issues#post2575950

**Comment by umezawatakeshi** [comment]
Yes, I have heard same false positive issue from other users, too. I have sent false positive report to some AV vendors.

The above mentioned report makes whitelisting **the** reported installer package, not packages built in the future. The freshly built package is also false-detected, so I have to report them each release time. Reporting false positive does not solve this issue.

However, because there is no clear (= publicly documented) standard for detecting malware, it is not possible to avoid false detection by me and there is not fundamental solution for this issue.

**Comment by oyvindln** [comment]
Ok, thanks for the reply, and for this great codec.
