### ISSUE TITLE
Adobe Premiere Pro/Media Encoder plugins support

### ISSUE THREAD

**Issue by PCUser2021** [umezawatakeshi/utvideo#42]
Please add Adobe Premiere Pro/Media Encoder plugins.

Thanks

**Comment by umezawatakeshi** [comment]
Unfortunately, I have no money to keep subscribing to Adobe products just to maintain the plugins.

**Comment by umezawatakeshi** [comment]
Wait wait wait. I mean that the subscription is needed during the plugin's lifetime. That is, if you stop sending me subscription coupons (i.e. stop bearing the cost of subscription) in the future, the plugin will be removed at that time. Are you REALLY ready for that?

Incidentally, I will not receive something like coupon or subscription code itself.

**Comment by PCUser2021** [comment]
I've lifetime license codes, do you really like to use these codes forever? (For After Effects, Premiere Pro, and Adobe Media Encoder) please just DM me to send you codes.

**Comment by PCUser2021** [comment]
Please send me your email address.

**Comment by umezawatakeshi** [comment]
Well, you are just a single GitHub user who opened this issue a few days ago for me. I don't know who/what you are and why you are able to issue a perpetual license of Pr/Ae/ME CC and to send it to me. Even if you explain who/what/why, I have no way to verify them in order to trust you.

You can find my email address used for receiving donation in "About donations" page in my blog. However, even if you send me a code, I will not receive it, at least not until I verify who/what/why.
